version: '3'
services:
  ngnix:
    image: nginx
    container_name: nginx
    volumes:
      - /home/ubuntu/site/yandex.clock/html:/usr/share/nginx/html:ro 
      - /home/ubuntu/site/yandex.clock/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Europe/Moscow
    ports:
      - 80:80
      - 443:443
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://10.128.0.12:12401'
        tag: nginx
    restart: always